# Generated by Django 5.2.6 on 2025-09-11 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_id', models.CharField(help_text='Slack team ID', max_length=50, unique=True)),
                ('team_name', models.CharField(help_text='Slack team/workspace name', max_length=255)),
                ('team_domain', models.CharField(blank=True, help_text='Slack team domain', max_length=255, null=True)),
                ('team_url', models.URLField(blank=True, help_text='Slack workspace URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workspace is active')),
            ],
            options={
                'verbose_name': 'Slack Workspace',
                'verbose_name_plural': 'Slack Workspaces',
                'db_table': 'slack_workspaces',
            },
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_user_id', models.CharField(help_text='Slack user ID', max_length=50)),
                ('slack_username', models.CharField(blank=True, help_text='Slack username', max_length=255, null=True)),
                ('slack_email', models.EmailField(blank=True, help_text='Slack user email', max_length=254, null=True)),
                ('access_token', models.TextField(help_text='Slack OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Slack OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('scopes', models.TextField(help_text='Granted OAuth scopes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user connection is active')),
                ('user', models.ForeignKey(help_text='Django user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Slack workspace', on_delete=django.db.models.deletion.CASCADE, to='core.slackworkspace')),
            ],
            options={
                'verbose_name': 'Slack User',
                'verbose_name_plural': 'Slack Users',
                'db_table': 'slack_users',
                'unique_together': {('workspace', 'slack_user_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(help_text='Slack channel ID', max_length=50)),
                ('channel_name', models.CharField(blank=True, help_text='Channel name', max_length=255, null=True)),
                ('channel_type', models.CharField(choices=[('public_channel', 'Public Channel'), ('private_channel', 'Private Channel'), ('im', 'Direct Message'), ('mpim', 'Multi-person Direct Message')], help_text='Type of channel', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='Whether channel is private')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether channel is archived')),
                ('workspace', models.ForeignKey(help_text='Slack workspace', on_delete=django.db.models.deletion.CASCADE, to='core.slackworkspace')),
            ],
            options={
                'verbose_name': 'Slack Channel',
                'verbose_name_plural': 'Slack Channels',
                'db_table': 'slack_channels',
                'unique_together': {('workspace', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_user_id', models.CharField(help_text='Bot user ID', max_length=50)),
                ('bot_access_token', models.TextField(help_text='Bot access token')),
                ('bot_scopes', models.TextField(help_text='Bot OAuth scopes')),
                ('app_id', models.CharField(blank=True, help_text='Slack app ID', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bot is active')),
                ('workspace', models.OneToOneField(help_text='Slack workspace', on_delete=django.db.models.deletion.CASCADE, to='core.slackworkspace')),
            ],
            options={
                'verbose_name': 'Slack Bot',
                'verbose_name_plural': 'Slack Bots',
                'db_table': 'slack_bots',
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_ts', models.CharField(help_text='Slack message timestamp', max_length=50)),
                ('message_type', models.CharField(choices=[('message', 'Message'), ('file_share', 'File Share'), ('channel_join', 'Channel Join'), ('channel_leave', 'Channel Leave')], default='message', help_text='Type of message', max_length=20)),
                ('text', models.TextField(blank=True, help_text='Message text', null=True)),
                ('thread_ts', models.CharField(blank=True, help_text='Thread timestamp', max_length=50, null=True)),
                ('is_thread_reply', models.BooleanField(default=False, help_text='Whether this is a thread reply')),
                ('channel', models.ForeignKey(help_text='Slack channel', on_delete=django.db.models.deletion.CASCADE, to='core.slackchannel')),
                ('slack_user', models.ForeignKey(blank=True, help_text='Message sender', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.slackuser')),
                ('workspace', models.ForeignKey(help_text='Slack workspace', on_delete=django.db.models.deletion.CASCADE, to='core.slackworkspace')),
            ],
            options={
                'verbose_name': 'Slack Message',
                'verbose_name_plural': 'Slack Messages',
                'db_table': 'slack_messages',
                'unique_together': {('workspace', 'channel', 'message_ts')},
            },
        ),
    ]
