# Generated by Django 5.2.6 on 2025-09-13 10:29

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_identifier', models.CharField(help_text='Unique identifier for the client (used in URLs and API calls)', max_length=100, unique=True)),
                ('app_name', models.CharField(help_text='Display name for the Slack app', max_length=255)),
                ('client_id', apps.core.models.EncryptedTextField(help_text='Slack app client ID')),
                ('client_secret', apps.core.models.EncryptedTextField(help_text='Slack app client secret')),
                ('signing_secret', apps.core.models.EncryptedTextField(help_text='Slack app signing secret')),
                ('redirect_uri', models.URLField(help_text='OAuth redirect URI for this client')),
                ('scopes', models.TextField(default='channels:read,chat:write,files:write,users:read', help_text='Comma-separated list of OAuth scopes')),
                ('client_name', models.CharField(help_text='Human-readable client name', max_length=255)),
                ('client_email', models.EmailField(blank=True, help_text='Contact email for the client', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the configuration has been verified to work')),
                ('verification_errors', models.TextField(blank=True, help_text='Last verification error messages', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this configuration was last used', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this configuration has been used')),
            ],
            options={
                'verbose_name': 'Slack App Configuration',
                'verbose_name_plural': 'Slack App Configurations',
                'db_table': 'slack_app_configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='slackworkspace',
            name='app_config',
            field=models.ForeignKey(blank=True, help_text='Associated Slack app configuration (for multi-tenant support)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.slackappconfiguration'),
        ),
    ]
