# Generated by Django 5.2.6 on 2025-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_slack_app_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackappconfiguration',
            name='scopes',
            field=models.TextField(default='channels:read,groups:read,chat:write,files:write,users:read,channels.join', help_text='Comma-separated list of OAuth scopes'),
        ),
    ]
