# Generated by Django 5.2.6 on 2025-09-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_slackappconfiguration_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackappconfiguration',
            name='scopes',
            field=models.TextField(default='channels:read,groups:read,chat:write,files:write,users:read,channels.join,im:write', help_text='Comma-separated list of OAuth scopes'),
        ),
    ]
