# Generated by Django 5.2.6 on 2025-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_existing_scopes_with_im_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackappconfiguration',
            name='scopes',
            field=models.TextField(default='channels:read,groups:read,im:read,mpim:read,chat:write,files:write,users:read,im:write,mpim:write,users:read.email', help_text='Comma-separated list of OAuth scopes'),
        ),
    ]
